SCALE_FACTOR: 2
SEQUENCE_SIZE: 3

MODEL:
  IN_CHANNELS: 3
  OUT_CHANNELS: 3
  FLOW_CHANNELS: 2
  BASE_1_CHANNELS: 256
  BASE_2_CHANNELS: 64

  SRNET_A:
    STAGE: 3

  SRNET_B:
    STAGE: 5

  SRNET_C:
    STAGE: 5

  SRNET_D:
    STAGE: 5

TRAIN:
  EPOCH: 100
  BATCH_SIZE: 32
  LEARNING_RATE: 1e-4
  DATASET:
    DATA_AUGMENTATION: True
    PATCH_SIZE: 64

TEST:
  BATCH_SIZE: 1
  DATASET:
    DATA_AUGMENTATION: False
    PATCH_SIZE: 0
