from yacs.config import CfgNode as CN

_C = CN()
_C.SCALE_FACTOR = 2
_C.SEQUENCE_SIZE = 7

_C.MODEL = CN()
_C.MODEL.IN_CHANNELS = 3
_C.MODEL.OUT_CHANNELS = 3
_C.MODEL.FLOW_CHANNELS = 2
_C.MODEL.BASE_1_CHANNELS = 256
_C.MODEL.BASE_2_CHANNELS = 64

_C.MODEL.SRNET_A = CN()
_C.MODEL.SRNET_A.STAGE = 3

_C.MODEL.SRNET_B = CN()
_C.MODEL.SRNET_B.STAGE = 5

_C.MODEL.SRNET_C = CN()
_C.MODEL.SRNET_C.STAGE = 5

_C.MODEL.SRNET_D = CN()
_C.MODEL.SRNET_D.STAGE = 5

_C.TRAIN = CN()
_C.TRAIN.EPOCH = 100
_C.TRAIN.BATCH_SIZE = 32
_C.TRAIN.LEARNING_RATE = 1e-4

_C.TRAIN.DATASET = CN()
_C.TRAIN.DATASET.DATA_AUGMENTATION = True
_C.TRAIN.DATASET.PATCH_SIZE = 64

_C.TEST = CN()
_C.TEST.BATCH_SIZE = 32

_C.TEST.DATASET = CN()
_C.TEST.DATASET.DATA_AUGMENTATION = False
_C.TEST.DATASET.PATCH_SIZE = 0
